version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    ports:
      - "27017:27017"
    volumes:
      - /home/tientcheudonald237/Documents/projet/spring/first/product-service/data:/data/db
